development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://default:oBtF3EtRSCpLhOvtGrjU5Be7bsCW8lJq@redis-18889.c268.eu-west-1-2.ec2.cloud.redislabs.com:18889") { "redis://localhost:6379/1" } %>
  channel_prefix: sportswap_production
