meta_product_name: "Sportswap!"
meta_title: "Sportswap! - sharing is caring"
meta_description: "Be a part of the Sharing economy and rent your sports equipment"
meta_image: "cover.png"
twitter_account: "@Sportswap_twitter_account"